os:
  - linux
  # - osx  # As of 2/28/17 Travis does not support Python in osx

language: python

python:
  - "3.6"

install:
 - pip3 install -r requirements.txt
 - pip3 install -r tests/test_requirements.txt
 - pip3 install -e ./

before_script:
  # Set up X server for Qt tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
 - pytest
 - bash doc/deploy_site.sh
env:
  global:
  - ENCRYPTION_LABEL: "56df1d613926"
  - COMMIT_AUTHOR_EMAIL: "andrewyoon2@gmail.com"
