language: python
sudo: required
dist: xenial

python:
  - "3.5"

install:
 - sudo apt-get update
 - sudo apt-get -y install python3-pyqt5
 - pip3 install -e ./
 - pip3 install -r requirements.txt
 - pip3 install -r tests/test_requirements.txt

script:
 - pytest
