language: python
sudo: required
dist: xenial

python:
  - "3.6"

install:
 - sudo apt-get update
 - sudo apt-get -y install python3-pyqt5
 - pip3 install -r requirements.txt
 - pip3 install -r tests/test_requirements.txt
 - pip3 install -e ./

before_script:
  # Set up X server for Qt tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
 - nosetests -v --processes=1 --process-restartworker
